movement_speed = 15
onclick_event_chance = 20 
left = false
flip_vertical = false
flip_horizontal = false
x = 10
y = 1025
debug = true
signal_frequency = 1
automatic_reload = false
sprites_path = "$HOME/.config/homie/sprites/current_sprites/"
fps = 7
width = 60
