movement_speed = 25
onclick_event_chance = 15
left = false
flip_vertical = false
flip_horizontal = false
x = 100
y = 1025
debug = true
signal_frequency = 1
automatic_reload = false
sprites_path = "$HOME/.config/homie/sprites/current_sprites/"
fps = 10
width = 100
